# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8641a32a64d65134f89727621cd5d28bbd540f951715eefa3513e72f274cae289d016ea7321bd957b4c926f7ffbbc52f2c3267690532495fa1c9ef688e50aeb4

test:
  secret_key_base: 3074783c1dd6af63945f203a74d9803a87df678903154ad2a4d1cb3e3a681ad29015f6aefc8d283f395846210b90852f2d856439fbff8f844943d61b7e2ffca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
